version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: secure-file-db
    restart: always
    env_file:
      - backend/.env
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: securefilesharing
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: secure-file-backend
    restart: always
    env_file:
      - backend/.env
    volumes:
      - media:/app/media
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: secure-file-frontend
    restart: always
    env_file:
      - frontend/.env
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  postgres_data:
  media:
